services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 9000:80

  mysql_db:
    container_name: dbmaria
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_docker
    ports:
      - 3307:3306

  redis_db:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379"